import com.thoughtworks.xstream.converters.reflection.AbstractAttributedCharacterIteratorAttributeConverter;
public class FunctionUse112 {
public void funcUse() {
AbstractAttributedCharacterIteratorAttributeConverter abstractattributedcharacteriteratorattributeconverter = new AbstractAttributedCharacterIteratorAttributeConverter();
abstractattributedcharacteriteratorattributeconverter.getName(null);
}
}